
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db1.cydxdfxuy77g.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
    password: 1q2w3e4r
  mail:
    host: smtp.gmail.com
    port: 587
    username: seonggwangdev@gmail.com
    password: dtblupqdigjthejx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: twG4VJ7R8xclhOehC1aiaP2B+Oh3Fw+8MrONXrjK8onafWdrbGip0LoXYGXOO7F36OT9qouRKD8kXqH0CUFmcw==